# Generated by Django 4.2.5 on 2023-10-05 17:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField(help_text='Idade em anos')),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('leite_diario', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('numero_de_crias', models.IntegerField(default=0)),
                ('esta_prenha', models.BooleanField(default=False)),
                ('esta_amamentando', models.BooleanField(default=False)),
                ('esta_no_cio', models.BooleanField(default=False)),
                ('esta_doente', models.BooleanField(default=False)),
                ('semana_de_gestacao', models.IntegerField(default=0)),
                ('ultima_inseminacao', models.DateTimeField(blank=True, null=True)),
                ('ultima_paricao', models.DateTimeField(blank=True, null=True)),
                ('ultima_pesagem', models.DateTimeField(blank=True, null=True)),
                ('ultima_vacinacao', models.DateTimeField(blank=True, null=True)),
                ('ultima_vermifugacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLeite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vacas')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('funcao', models.CharField(max_length=100)),
                ('esta_trabalhando', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filhote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField(help_text='Idade em anos')),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vacas')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
