# Generated by Django 4.2.5 on 2023-09-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome',
            new_name='servico',
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.servico')),
            ],
        ),
    ]
