# Generated by Django 4.2.5 on 2023-09-18 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_alter_preco_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.cliente'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='appointments.servico'),
        ),
    ]
